name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      if: endsWith(github.repository, 'python')
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Setup Node.js
      if: endsWith(github.repository, 'node')
      run: npm install

    - name: Deploy App
      run: |
        if [ -f "app.py" ]; then
          python app.py
        elif [ -f "app.js" ]; then
          node app.js
        fi
